"""baseline schema

Revision ID: 284feb88a8ef
Revises:
Create Date: 2026-05-11 19:33:42.966194+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "284feb88a8ef"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tech_dimensions",
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("order_no", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tech_dimensions")),
        sa.UniqueConstraint("slug", name=op.f("uq_tech_dimensions__slug")),
    )
    op.create_table(
        "tenants",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenants")),
    )
    op.create_table(
        "users",
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("role", sa.String(length=32), server_default="owner", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "role IN ('owner', 'member', 'readonly')", name=op.f("ck_users__role_valid")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users__email")),
    )
    op.create_table(
        "projects",
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("owner_user_id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("objective", sa.Text(), nullable=False),
        sa.Column("context_md", sa.Text(), nullable=True),
        sa.Column("card_code_prefix", sa.String(length=8), nullable=False),
        sa.Column(
            "card_template", sa.String(length=32), server_default="phase_vli", nullable=False
        ),
        sa.Column("grouping", sa.String(length=16), server_default="phase", nullable=False),
        sa.Column("status", sa.String(length=16), server_default="draft", nullable=False),
        sa.Column("llm_provider", sa.String(length=16), server_default="anthropic", nullable=False),
        sa.Column("llm_model", sa.Text(), server_default="claude-sonnet-4-5", nullable=False),
        sa.Column(
            "llm_temperature",
            sa.Numeric(precision=3, scale=2),
            server_default="0.20",
            nullable=False,
        ),
        sa.Column("llm_enable_reasoning", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "card_template IN ('phase_vli', 'strict_9', 'free_form')",
            name=op.f("ck_projects__card_template_valid"),
        ),
        sa.CheckConstraint(
            "grouping IN ('phase', 'epic', 'flat')", name=op.f("ck_projects__grouping_valid")
        ),
        sa.CheckConstraint(
            "llm_provider IN ('anthropic', 'openai', 'ollama')",
            name=op.f("ck_projects__llm_provider_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'in_progress', 'exported', 'archived')",
            name=op.f("ck_projects__status_valid"),
        ),
        sa.CheckConstraint(
            "char_length(card_code_prefix) BETWEEN 2 AND 8",
            name=op.f("ck_projects__card_code_prefix_length"),
        ),
        sa.CheckConstraint(
            "llm_temperature >= 0.00 AND llm_temperature <= 2.00",
            name=op.f("ck_projects__llm_temperature_range"),
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_projects__owner_user_id__users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("fk_projects__tenant_id__tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
        sa.UniqueConstraint("tenant_id", "slug", name="tenant_slug"),
    )
    op.create_table(
        "tech_items",
        sa.Column("dimension_id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "tags", sa.ARRAY(sa.Text()), server_default=sa.text("ARRAY[]::text[]"), nullable=False
        ),
        sa.Column("is_custom", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_tech_items__created_by_user_id__users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["dimension_id"],
            ["tech_dimensions.id"],
            name=op.f("fk_tech_items__dimension_id__tech_dimensions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tech_items")),
        sa.UniqueConstraint("dimension_id", "slug", name="dimension_slug"),
    )
    op.create_index(
        "ix_tech_items__dimension_name", "tech_items", ["dimension_id", "name"], unique=False
    )
    op.create_table(
        "exports",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("target_path", sa.Text(), nullable=True),
        sa.Column("manifest_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "kind IN ('filesystem', 'zip', 'jira_csv')", name=op.f("ck_exports__kind_valid")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_exports__project_id__projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exports")),
    )
    op.create_table(
        "llm_runs",
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("provider", sa.String(length=16), nullable=False),
        sa.Column("model", sa.Text(), nullable=False),
        sa.Column("prompt_messages_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("response_text", sa.Text(), nullable=True),
        sa.Column("response_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("reasoning_md", sa.Text(), nullable=True),
        sa.Column("reasoning_tokens", sa.Integer(), nullable=True),
        sa.Column("reasoning_truncated", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "extended_thinking_enabled", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("tokens_in", sa.Integer(), nullable=True),
        sa.Column("tokens_out", sa.Integer(), nullable=True),
        sa.Column("cost_usd", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "kind IN ('propose_skill_set', 'draft_skill_body', 'propose_backlog', 'draft_card', 'suggest_tech', 'other')",
            name=op.f("ck_llm_runs__kind_valid"),
        ),
        sa.CheckConstraint(
            "provider IN ('anthropic', 'openai', 'ollama')",
            name=op.f("ck_llm_runs__provider_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('success', 'parse_error', 'provider_error', 'in_progress')",
            name=op.f("ck_llm_runs__status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_llm_runs__project_id__projects"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_llm_runs")),
    )
    op.create_index(
        "ix_llm_runs__project_created", "llm_runs", ["project_id", "created_at"], unique=False
    )
    op.create_table(
        "phases",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description_md", sa.Text(), nullable=True),
        sa.Column("order_no", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_phases__project_id__projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_phases")),
        sa.UniqueConstraint("project_id", "code", name="project_code"),
    )
    op.create_table(
        "project_artifacts",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("filename", sa.Text(), nullable=False),
        sa.Column("mime_type", sa.Text(), nullable=True),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column(
            "extraction_status", sa.String(length=16), server_default="pending", nullable=False
        ),
        sa.Column("extraction_error", sa.Text(), nullable=True),
        sa.Column("extracted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("extractor_used", sa.String(length=32), nullable=True),
        sa.Column("content_md", sa.Text(), nullable=True),
        sa.Column("content_md_truncated", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "extraction_status IN ('pending', 'extracting', 'extracted', 'failed')",
            name=op.f("ck_project_artifacts__extraction_status_valid"),
        ),
        sa.CheckConstraint(
            "kind IN ('doc', 'code', 'spec', 'glossary', 'other')",
            name=op.f("ck_project_artifacts__kind_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_project_artifacts__project_id__projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_artifacts")),
    )
    op.create_index(
        "ix_project_artifacts__project_status",
        "project_artifacts",
        ["project_id", "extraction_status"],
        unique=False,
    )
    op.create_table(
        "project_qa_answers",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("question_key", sa.String(length=64), nullable=False),
        sa.Column("answer_md", sa.Text(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "question_key IN ('business_problem', 'success_definition', 'users_and_actors', 'must_preserve', 'must_change', 'compliance', 'known_gaps')",
            name=op.f("ck_project_qa_answers__question_key_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_project_qa_answers__project_id__projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("project_id", "question_key", name=op.f("pk_project_qa_answers")),
    )
    op.create_table(
        "project_tech_choices",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("dimension_id", sa.UUID(), nullable=False),
        sa.Column("tech_item_id", sa.UUID(), nullable=True),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("source", sa.String(length=16), server_default="catalog", nullable=False),
        sa.Column("accepted", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("llm_rationale", sa.Text(), nullable=True),
        sa.Column("llm_confidence", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("order_no", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "(role = 'tbd' AND tech_item_id IS NULL) OR (role <> 'tbd' AND tech_item_id IS NOT NULL)",
            name=op.f("ck_project_tech_choices__tbd_requires_null_item"),
        ),
        sa.CheckConstraint(
            "role IN ('target', 'legacy', 'optional', 'must_avoid', 'tbd')",
            name=op.f("ck_project_tech_choices__role_valid"),
        ),
        sa.CheckConstraint(
            "source IN ('catalog', 'user_added', 'llm_suggested')",
            name=op.f("ck_project_tech_choices__source_valid"),
        ),
        sa.CheckConstraint(
            "llm_confidence IS NULL OR (llm_confidence >= 0 AND llm_confidence <= 1)",
            name=op.f("ck_project_tech_choices__llm_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["dimension_id"],
            ["tech_dimensions.id"],
            name=op.f("fk_project_tech_choices__dimension_id__tech_dimensions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_project_tech_choices__project_id__projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tech_item_id"],
            ["tech_items.id"],
            name=op.f("fk_project_tech_choices__tech_item_id__tech_items"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_tech_choices")),
    )
    op.create_index(
        "ix_project_tech_choices__project_dim_order",
        "project_tech_choices",
        ["project_id", "dimension_id", "order_no"],
        unique=False,
    )
    op.create_index(
        "uq_project_tech_choices__project_dimension_item",
        "project_tech_choices",
        ["project_id", "dimension_id", "tech_item_id"],
        unique=True,
        postgresql_where=sa.text("tech_item_id IS NOT NULL"),
    )
    op.create_table(
        "skills",
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("body_md", sa.Text(), server_default="", nullable=False),
        sa.Column("order_no", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('context', 'authoring', 'analyzer', 'procedure')",
            name=op.f("ck_skills__kind_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_skills__project_id__projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_skills")),
        sa.UniqueConstraint("project_id", "slug", name="project_slug"),
    )
    op.create_table(
        "cards",
        sa.Column("phase_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("type", sa.String(length=16), nullable=False),
        sa.Column("story_points", sa.Integer(), nullable=True),
        sa.Column("priority", sa.String(length=16), nullable=True),
        sa.Column("status", sa.String(length=16), server_default="draft", nullable=False),
        sa.Column("human_gate", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("human_gate_checklist_md", sa.Text(), nullable=True),
        sa.Column("context_md", sa.Text(), nullable=True),
        sa.Column("task_md", sa.Text(), nullable=True),
        sa.Column("outputs_md", sa.Text(), nullable=True),
        sa.Column("acceptance_criteria_md", sa.Text(), nullable=True),
        sa.Column("order_no", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "priority IS NULL OR priority IN ('Low', 'Medium', 'High')",
            name=op.f("ck_cards__priority_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'ready', 'in_progress', 'done')",
            name=op.f("ck_cards__status_valid"),
        ),
        sa.CheckConstraint(
            "type IN ('Task', 'Story', 'Bug', 'Spike', 'Demo')", name=op.f("ck_cards__type_valid")
        ),
        sa.CheckConstraint(
            "(human_gate = false) OR (human_gate_checklist_md IS NOT NULL AND char_length(human_gate_checklist_md) > 0)",
            name=op.f("ck_cards__gate_requires_checklist"),
        ),
        sa.ForeignKeyConstraint(
            ["phase_id"], ["phases.id"], name=op.f("fk_cards__phase_id__phases"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cards")),
        sa.UniqueConstraint("phase_id", "code", name="phase_code"),
    )
    op.create_index("ix_cards__code", "cards", ["code"], unique=False)
    op.create_index("ix_cards__phase_order", "cards", ["phase_id", "order_no"], unique=False)
    op.create_table(
        "skill_resources",
        sa.Column("skill_id", sa.UUID(), nullable=False),
        sa.Column("filename", sa.Text(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("language", sa.String(length=16), server_default="markdown", nullable=False),
        sa.Column("order_no", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "language IN ('markdown', 'sql', 'yaml', 'python', 'plain')",
            name=op.f("ck_skill_resources__language_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skills.id"],
            name=op.f("fk_skill_resources__skill_id__skills"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_skill_resources")),
        sa.UniqueConstraint("skill_id", "filename", name="skill_filename"),
    )
    op.create_table(
        "card_deps",
        sa.Column("card_id", sa.UUID(), nullable=False),
        sa.Column("depends_on_card_id", sa.UUID(), nullable=False),
        sa.Column("relation", sa.String(length=16), server_default="depends_on", nullable=False),
        sa.CheckConstraint(
            "relation IN ('depends_on', 'parallel_with')", name=op.f("ck_card_deps__relation_valid")
        ),
        sa.CheckConstraint("card_id <> depends_on_card_id", name=op.f("ck_card_deps__no_self_dep")),
        sa.ForeignKeyConstraint(
            ["card_id"], ["cards.id"], name=op.f("fk_card_deps__card_id__cards"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["depends_on_card_id"],
            ["cards.id"],
            name=op.f("fk_card_deps__depends_on_card_id__cards"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "card_id", "depends_on_card_id", "relation", name=op.f("pk_card_deps")
        ),
    )
    op.create_index("ix_card_deps__depends_on", "card_deps", ["depends_on_card_id"], unique=False)
    op.create_table(
        "card_inputs",
        sa.Column("card_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("label", sa.Text(), nullable=True),
        sa.Column("order_no", sa.Integer(), server_default="0", nullable=False),
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "kind IN ('skill_resource', 'artifact', 'external')",
            name=op.f("ck_card_inputs__kind_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["cards.id"],
            name=op.f("fk_card_inputs__card_id__cards"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_card_inputs")),
    )
    op.create_table(
        "card_skills",
        sa.Column("card_id", sa.UUID(), nullable=False),
        sa.Column("skill_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["cards.id"],
            name=op.f("fk_card_skills__card_id__cards"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skills.id"],
            name=op.f("fk_card_skills__skill_id__skills"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("card_id", "skill_id", name=op.f("pk_card_skills")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("card_skills")
    op.drop_table("card_inputs")
    op.drop_index("ix_card_deps__depends_on", table_name="card_deps")
    op.drop_table("card_deps")
    op.drop_table("skill_resources")
    op.drop_index("ix_cards__phase_order", table_name="cards")
    op.drop_index("ix_cards__code", table_name="cards")
    op.drop_table("cards")
    op.drop_table("skills")
    op.drop_index(
        "uq_project_tech_choices__project_dimension_item",
        table_name="project_tech_choices",
        postgresql_where=sa.text("tech_item_id IS NOT NULL"),
    )
    op.drop_index("ix_project_tech_choices__project_dim_order", table_name="project_tech_choices")
    op.drop_table("project_tech_choices")
    op.drop_table("project_qa_answers")
    op.drop_index("ix_project_artifacts__project_status", table_name="project_artifacts")
    op.drop_table("project_artifacts")
    op.drop_table("phases")
    op.drop_index("ix_llm_runs__project_created", table_name="llm_runs")
    op.drop_table("llm_runs")
    op.drop_table("exports")
    op.drop_index("ix_tech_items__dimension_name", table_name="tech_items")
    op.drop_table("tech_items")
    op.drop_table("projects")
    op.drop_table("users")
    op.drop_table("tenants")
    op.drop_table("tech_dimensions")
    # ### end Alembic commands ###
